//------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//     Generator      : XSharp.CodeDomProvider 2.18.0.4
//     Timestamp      : 31.03.2024 23:15:14
//     
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
//  </auto-generated>
//------------------------------------------------------------------------------
BEGIN NAMESPACE EFReferenceChecker

    PUBLIC PARTIAL CLASS MainForm

        /// <summary>
        /// Required designer variable.
        /// </summary>
        PRIVATE components := NULL AS System.ComponentModel.IContainer
        PRIVATE tableLayoutPanel1 AS System.Windows.Forms.TableLayoutPanel
        PRIVATE panel1 AS System.Windows.Forms.Panel
        PRIVATE bntStart AS System.Windows.Forms.Button
        PRIVATE btnChooseBinFolder AS System.Windows.Forms.Button
        PRIVATE lsvStatus AS System.Windows.Forms.ListView
        PRIVATE progressBar1 AS System.Windows.Forms.ProgressBar
        PRIVATE label1 AS System.Windows.Forms.Label

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        PROTECTED OVERRIDE METHOD Dispose(disposing AS LOGIC) AS VOID STRICT

            IF (disposing .and. (components != null))
                components:Dispose()
            ENDIF
            SUPER:Dispose(disposing)
			RETURN
        END METHOD
        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
                                                                                                PRIVATE METHOD InitializeComponent() AS VOID STRICT
            SELF:tableLayoutPanel1 := System.Windows.Forms.TableLayoutPanel{}
            SELF:panel1 := System.Windows.Forms.Panel{}
            SELF:btnChooseBinFolder := System.Windows.Forms.Button{}
            SELF:bntStart := System.Windows.Forms.Button{}
            SELF:lsvStatus := System.Windows.Forms.ListView{}
            SELF:label1 := System.Windows.Forms.Label{}
            SELF:progressBar1 := System.Windows.Forms.ProgressBar{}
            SELF:tableLayoutPanel1:SuspendLayout()
            SELF:panel1:SuspendLayout()
            SELF:SuspendLayout()
            // 
            // tableLayoutPanel1
            // 
            SELF:tableLayoutPanel1:ColumnCount := 1
            SELF:tableLayoutPanel1:ColumnStyles:Add(System.Windows.Forms.ColumnStyle{System.Windows.Forms.SizeType.Percent, 50})
            SELF:tableLayoutPanel1:Controls:Add(SELF:lsvStatus, 0, 1)
            SELF:tableLayoutPanel1:Controls:Add(SELF:panel1, 0, 0)
            SELF:tableLayoutPanel1:Dock := System.Windows.Forms.DockStyle.Fill
            SELF:tableLayoutPanel1:Location := System.Drawing.Point{0, 0}
            SELF:tableLayoutPanel1:Name := "tableLayoutPanel1"
            SELF:tableLayoutPanel1:RowCount := 3
            SELF:tableLayoutPanel1:RowStyles:Add(System.Windows.Forms.RowStyle{System.Windows.Forms.SizeType.Percent, 27.8965988})
            SELF:tableLayoutPanel1:RowStyles:Add(System.Windows.Forms.RowStyle{System.Windows.Forms.SizeType.Percent, 62.5584068})
            SELF:tableLayoutPanel1:RowStyles:Add(System.Windows.Forms.RowStyle{System.Windows.Forms.SizeType.Percent, 9.544994})
            SELF:tableLayoutPanel1:Size := System.Drawing.Size{650, 740}
            SELF:tableLayoutPanel1:TabIndex := 0
            // 
            // panel1
            // 
            SELF:panel1:BackColor := System.Drawing.Color.FromArgb(((INT)(((BYTE)(192)))), ((INT)(((BYTE)(255)))), ((INT)(((BYTE)(192)))))
            SELF:panel1:Controls:Add(SELF:progressBar1)
            SELF:panel1:Controls:Add(SELF:label1)
            SELF:panel1:Controls:Add(SELF:bntStart)
            SELF:panel1:Controls:Add(SELF:btnChooseBinFolder)
            SELF:panel1:Dock := System.Windows.Forms.DockStyle.Fill
            SELF:panel1:Location := System.Drawing.Point{3, 3}
            SELF:panel1:Name := "panel1"
            SELF:panel1:Size := System.Drawing.Size{644, 200}
            SELF:panel1:TabIndex := 0
            // 
            // btnChooseBinFolder
            // 
            SELF:btnChooseBinFolder:Location := System.Drawing.Point{10, 23}
            SELF:btnChooseBinFolder:Name := "btnChooseBinFolder"
            SELF:btnChooseBinFolder:Size := System.Drawing.Size{136, 34}
            SELF:btnChooseBinFolder:TabIndex := 0
            SELF:btnChooseBinFolder:Text := "Bin-Verzeichnis"
            SELF:btnChooseBinFolder:UseVisualStyleBackColor := TRUE
            // 
            // bntStart
            // 
            SELF:bntStart:Location := System.Drawing.Point{10, 63}
            SELF:bntStart:Name := "bntStart"
            SELF:bntStart:Size := System.Drawing.Size{136, 34}
            SELF:bntStart:TabIndex := 1
            SELF:bntStart:Text := "&Start"
            SELF:bntStart:UseVisualStyleBackColor := TRUE
            // 
            // lsvStatus
            // 
            SELF:lsvStatus:BackColor := System.Drawing.Color.FromArgb(((INT)(((BYTE)(255)))), ((INT)(((BYTE)(255)))), ((INT)(((BYTE)(192)))))
            SELF:lsvStatus:Dock := System.Windows.Forms.DockStyle.Fill
            SELF:lsvStatus:HideSelection := FALSE
            SELF:lsvStatus:Location := System.Drawing.Point{3, 209}
            SELF:lsvStatus:Name := "lsvStatus"
            SELF:lsvStatus:Size := System.Drawing.Size{644, 456}
            SELF:lsvStatus:TabIndex := 3
            SELF:lsvStatus:UseCompatibleStateImageBehavior := FALSE
            // 
            // label1
            // 
            SELF:label1:AutoEllipsis := TRUE
            SELF:label1:BackColor := System.Drawing.Color.FromArgb(((INT)(((BYTE)(255)))), ((INT)(((BYTE)(224)))), ((INT)(((BYTE)(192)))))
            SELF:label1:Location := System.Drawing.Point{169, 23}
            SELF:label1:Name := "label1"
            SELF:label1:Size := System.Drawing.Size{466, 34}
            SELF:label1:TabIndex := 2
            SELF:label1:Text := "label1"
            // 
            // progressBar1
            // 
            SELF:progressBar1:Location := System.Drawing.Point{167, 63}
            SELF:progressBar1:Name := "progressBar1"
            SELF:progressBar1:Size := System.Drawing.Size{468, 34}
            SELF:progressBar1:TabIndex := 3
            // 
            // MainForm
            // 
            SELF:AutoScaleDimensions := System.Drawing.SizeF{7, 20}
            SELF:AutoScaleMode := System.Windows.Forms.AutoScaleMode.Font
            SELF:ClientSize := System.Drawing.Size{650, 740}
            SELF:Controls:Add(SELF:tableLayoutPanel1)
            SELF:Font := System.Drawing.Font{"Arial Narrow", 11.25, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((BYTE)(0))}
            SELF:Margin := System.Windows.Forms.Padding{4, 5, 4, 5}
            SELF:Name := "MainForm"
            SELF:Text := "EF-Referenzchecker (v 0.1)"
            SELF:tableLayoutPanel1:ResumeLayout(false)
            SELF:panel1:ResumeLayout(FALSE)
            SELF:ResumeLayout(FALSE)
        END METHOD
        #endregion
    END CLASS 
END NAMESPACE
