//------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//     Generator      : XSharp.CodeDomProvider 2.18.0.4
//     Timestamp      : 01.04.2024 15:09:40
//     
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
//  </auto-generated>
//------------------------------------------------------------------------------
BEGIN NAMESPACE EFReferenceChecker

    PUBLIC PARTIAL CLASS MainForm

        /// <summary>
        /// Required designer variable.
        /// </summary>
        PRIVATE components := NULL AS System.ComponentModel.IContainer
        PRIVATE barAndDockingController1 AS DevExpress.XtraBars.BarAndDockingController
        PRIVATE grdAssemblies AS DevExpress.XtraGrid.GridControl
        PRIVATE gridView1 AS DevExpress.XtraGrid.Views.Grid.GridView
        PRIVATE panel1 AS System.Windows.Forms.Panel
        PRIVATE progressBar1 AS System.Windows.Forms.ProgressBar
        PRIVATE lblBinPath AS System.Windows.Forms.Label
        PRIVATE bntStart AS System.Windows.Forms.Button
        PRIVATE btnChooseBinFolder AS System.Windows.Forms.Button
        PRIVATE tableLayoutPanel1 AS System.Windows.Forms.TableLayoutPanel
        PRIVATE lsbStatus AS System.Windows.Forms.ListBox

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        PROTECTED OVERRIDE METHOD Dispose(disposing AS LOGIC) AS VOID STRICT

            IF (disposing .and. (components != null))
                components:Dispose()
            ENDIF
            SUPER:Dispose(disposing)
			RETURN
        END METHOD
        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
                                                                                                                                                                PRIVATE METHOD InitializeComponent() AS VOID STRICT
            SELF:components := System.ComponentModel.Container{}
            SELF:barAndDockingController1 := DevExpress.XtraBars.BarAndDockingController{SELF:components}
            SELF:grdAssemblies := DevExpress.XtraGrid.GridControl{}
            SELF:gridView1 := DevExpress.XtraGrid.Views.Grid.GridView{}
            SELF:panel1 := System.Windows.Forms.Panel{}
            SELF:progressBar1 := System.Windows.Forms.ProgressBar{}
            SELF:lblBinPath := System.Windows.Forms.Label{}
            SELF:bntStart := System.Windows.Forms.Button{}
            SELF:btnChooseBinFolder := System.Windows.Forms.Button{}
            SELF:tableLayoutPanel1 := System.Windows.Forms.TableLayoutPanel{}
            SELF:lsbStatus := System.Windows.Forms.ListBox{}
            ((System.ComponentModel.ISupportInitialize)(SELF:barAndDockingController1)):BeginInit()
            ((System.ComponentModel.ISupportInitialize)(SELF:grdAssemblies)):BeginInit()
            ((System.ComponentModel.ISupportInitialize)(SELF:gridView1)):BeginInit()
            SELF:panel1:SuspendLayout()
            SELF:tableLayoutPanel1:SuspendLayout()
            SELF:SuspendLayout()
            // 
            // barAndDockingController1
            // 
            SELF:barAndDockingController1:PropertiesBar:AllowLinkLighting := false
            // 
            // grdAssemblies
            // 
            SELF:grdAssemblies:Dock := System.Windows.Forms.DockStyle.Fill
            SELF:grdAssemblies:Location := System.Drawing.Point{3, 284}
            SELF:grdAssemblies:MainView := SELF:gridView1
            SELF:grdAssemblies:Name := "grdAssemblies"
            SELF:grdAssemblies:Size := System.Drawing.Size{644, 453}
            SELF:grdAssemblies:TabIndex := 1
            SELF:grdAssemblies:ViewCollection:AddRange(<DevExpress.XtraGrid.Views.Base.BaseView>{ SELF:gridView1 })
            // 
            // gridView1
            // 
            SELF:gridView1:GridControl := SELF:grdAssemblies
            SELF:gridView1:Name := "gridView1"
            // 
            // panel1
            // 
            SELF:panel1:BackColor := System.Drawing.Color.FromArgb(((INT)(((BYTE)(192)))), ((INT)(((BYTE)(255)))), ((INT)(((BYTE)(192)))))
            SELF:panel1:Controls:Add(SELF:progressBar1)
            SELF:panel1:Controls:Add(SELF:lblBinPath)
            SELF:panel1:Controls:Add(SELF:bntStart)
            SELF:panel1:Controls:Add(SELF:btnChooseBinFolder)
            SELF:panel1:Dock := System.Windows.Forms.DockStyle.Fill
            SELF:panel1:Location := System.Drawing.Point{3, 3}
            SELF:panel1:Name := "panel1"
            SELF:panel1:Size := System.Drawing.Size{644, 143}
            SELF:panel1:TabIndex := 0
            // 
            // progressBar1
            // 
            SELF:progressBar1:Location := System.Drawing.Point{167, 63}
            SELF:progressBar1:Name := "progressBar1"
            SELF:progressBar1:Size := System.Drawing.Size{468, 34}
            SELF:progressBar1:TabIndex := 3
            // 
            // lblBinPath
            // 
            SELF:lblBinPath:AutoEllipsis := true
            SELF:lblBinPath:BackColor := System.Drawing.Color.FromArgb(((INT)(((BYTE)(255)))), ((INT)(((BYTE)(224)))), ((INT)(((BYTE)(192)))))
            SELF:lblBinPath:Location := System.Drawing.Point{169, 23}
            SELF:lblBinPath:Name := "lblBinPath"
            SELF:lblBinPath:Size := System.Drawing.Size{466, 34}
            SELF:lblBinPath:TabIndex := 2
            // 
            // bntStart
            // 
            SELF:bntStart:Location := System.Drawing.Point{10, 63}
            SELF:bntStart:Name := "bntStart"
            SELF:bntStart:Size := System.Drawing.Size{136, 34}
            SELF:bntStart:TabIndex := 1
            SELF:bntStart:Text := "&Start"
            SELF:bntStart:UseVisualStyleBackColor := true
            SELF:bntStart:Click += System.EventHandler{ SELF, @bntStart_Click() }
            // 
            // btnChooseBinFolder
            // 
            SELF:btnChooseBinFolder:Location := System.Drawing.Point{10, 23}
            SELF:btnChooseBinFolder:Name := "btnChooseBinFolder"
            SELF:btnChooseBinFolder:Size := System.Drawing.Size{136, 34}
            SELF:btnChooseBinFolder:TabIndex := 0
            SELF:btnChooseBinFolder:Text := "Bin-Verzeichnis"
            SELF:btnChooseBinFolder:UseVisualStyleBackColor := true
            SELF:btnChooseBinFolder:Click += System.EventHandler{ SELF, @btnChooseBinFolder_Click() }
            // 
            // tableLayoutPanel1
            // 
            SELF:tableLayoutPanel1:ColumnCount := 1
            SELF:tableLayoutPanel1:ColumnStyles:Add(System.Windows.Forms.ColumnStyle{System.Windows.Forms.SizeType.Percent, 50})
            SELF:tableLayoutPanel1:Controls:Add(SELF:panel1, 0, 0)
            SELF:tableLayoutPanel1:Controls:Add(SELF:grdAssemblies, 0, 2)
            SELF:tableLayoutPanel1:Controls:Add(SELF:lsbStatus, 0, 1)
            SELF:tableLayoutPanel1:Dock := System.Windows.Forms.DockStyle.Fill
            SELF:tableLayoutPanel1:Location := System.Drawing.Point{0, 0}
            SELF:tableLayoutPanel1:Name := "tableLayoutPanel1"
            SELF:tableLayoutPanel1:RowCount := 3
            SELF:tableLayoutPanel1:RowStyles:Add(System.Windows.Forms.RowStyle{System.Windows.Forms.SizeType.Percent, 20.1351357})
            SELF:tableLayoutPanel1:RowStyles:Add(System.Windows.Forms.RowStyle{System.Windows.Forms.SizeType.Percent, 17.8378372})
            SELF:tableLayoutPanel1:RowStyles:Add(System.Windows.Forms.RowStyle{System.Windows.Forms.SizeType.Percent, 62.0270271})
            SELF:tableLayoutPanel1:Size := System.Drawing.Size{650, 740}
            SELF:tableLayoutPanel1:TabIndex := 0
            // 
            // lsbStatus
            // 
            SELF:lsbStatus:BackColor := System.Drawing.Color.FromArgb(((INT)(((BYTE)(255)))), ((INT)(((BYTE)(255)))), ((INT)(((BYTE)(192)))))
            SELF:lsbStatus:Dock := System.Windows.Forms.DockStyle.Fill
            SELF:lsbStatus:FormattingEnabled := true
            SELF:lsbStatus:ItemHeight := 20
            SELF:lsbStatus:Location := System.Drawing.Point{3, 152}
            SELF:lsbStatus:Name := "lsbStatus"
            SELF:lsbStatus:Size := System.Drawing.Size{644, 126}
            SELF:lsbStatus:TabIndex := 2
            // 
            // MainForm
            // 
            SELF:AutoScaleDimensions := System.Drawing.SizeF{7, 20}
            SELF:AutoScaleMode := System.Windows.Forms.AutoScaleMode.Font
            SELF:ClientSize := System.Drawing.Size{650, 740}
            SELF:Controls:Add(SELF:tableLayoutPanel1)
            SELF:Font := System.Drawing.Font{"Arial Narrow", 11.25, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((BYTE)(0))}
            SELF:FormBorderStyle := System.Windows.Forms.FormBorderStyle.FixedSingle
            SELF:Margin := System.Windows.Forms.Padding{4, 5, 4, 5}
            SELF:Name := "MainForm"
            SELF:Text := "EF-Referenzchecker (v 0.1)"
            ((System.ComponentModel.ISupportInitialize)(SELF:barAndDockingController1)):EndInit()
            ((System.ComponentModel.ISupportInitialize)(SELF:grdAssemblies)):EndInit()
            ((System.ComponentModel.ISupportInitialize)(SELF:gridView1)):EndInit()
            SELF:panel1:ResumeLayout(false)
            SELF:tableLayoutPanel1:ResumeLayout(false)
            SELF:ResumeLayout(false)
        END METHOD
        #endregion
    END CLASS 
END NAMESPACE
